// Mobile navigation
const menuToggle=document.querySelector('.menu-toggle');const mainNav=document.querySelector('.main-nav');if(menuToggle&&mainNav){menuToggle.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open?'true':'false')});}
// Active navigation fallback
const currentPage=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.main-nav a').forEach(a=>{if(a.getAttribute('href')===currentPage){a.classList.add('active')}});
// Scroll reveal animations
const revealEls=document.querySelectorAll('.reveal');const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}})},{threshold:.12});revealEls.forEach(el=>revealObserver.observe(el));
// Gallery lightbox
const galleryItems=[...document.querySelectorAll('.gallery-item')];const lightbox=document.querySelector('.lightbox');if(galleryItems.length&&lightbox){const img=lightbox.querySelector('img');const close=lightbox.querySelector('.lightbox-close');const prev=lightbox.querySelector('.lightbox-prev');const next=lightbox.querySelector('.lightbox-next');let index=0;const openLightbox=i=>{index=i;img.src=galleryItems[index].src;img.alt=galleryItems[index].alt;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};const closeLightbox=()=>{lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow=''};const move=step=>{index=(index+step+galleryItems.length)%galleryItems.length;img.src=galleryItems[index].src;img.alt=galleryItems[index].alt};galleryItems.forEach((item,i)=>item.addEventListener('click',()=>openLightbox(i)));close.addEventListener('click',closeLightbox);prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(!lightbox.classList.contains('open'))return;if(e.key==='Escape')closeLightbox();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});}
// Static form feedback before Web3Forms submission
const form=document.querySelector('.contact-form');if(form){const serviceBoxes=[...form.querySelectorAll('input[name="services[]"]')];const msg=form.querySelector('.form-message');const submitButton=form.querySelector('button[type="submit"]');const successModal=document.createElement('div');successModal.className='success-modal';successModal.setAttribute('aria-hidden','true');successModal.innerHTML='<div class="success-modal-panel" role="dialog" aria-modal="true" aria-labelledby="success-modal-title"><button class="success-modal-close" type="button" aria-label="Close success message">&times;</button><p class="section-kicker">Quote Request Sent</p><h3 id="success-modal-title">Message successfully sent.</h3><p>Thank you for your enquiry. SA Autec Industries will review your request and respond shortly.</p><button class="btn btn-primary success-modal-ok" type="button">Close</button></div>';document.body.appendChild(successModal);const closeSuccess=()=>{successModal.classList.remove('open');successModal.setAttribute('aria-hidden','true');document.body.style.overflow=''};const openSuccess=()=>{successModal.classList.add('open');successModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';successModal.querySelector('.success-modal-ok').focus()};successModal.querySelector('.success-modal-close').addEventListener('click',closeSuccess);successModal.querySelector('.success-modal-ok').addEventListener('click',closeSuccess);successModal.addEventListener('click',e=>{if(e.target===successModal)closeSuccess()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&successModal.classList.contains('open'))closeSuccess()});const requestedService=new URLSearchParams(location.search).get('service');if(requestedService){serviceBoxes.forEach(box=>{if(box.value.toLowerCase()===requestedService.toLowerCase())box.checked=true});}const updateServiceValidity=()=>{if(!serviceBoxes.length)return;const checked=serviceBoxes.some(box=>box.checked);serviceBoxes[0].setCustomValidity(checked?'':'Please select at least one service or product.');};serviceBoxes.forEach(box=>box.addEventListener('change',updateServiceValidity));updateServiceValidity();form.addEventListener('submit',async e=>{e.preventDefault();updateServiceValidity();if(!form.checkValidity()){form.reportValidity();return;}if(msg)msg.textContent='Submitting your quote request...';if(submitButton)submitButton.disabled=true;try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});const result=await response.json();if(response.ok&&result.success){form.reset();updateServiceValidity();if(msg)msg.textContent='';openSuccess();}else{throw new Error(result.message||'Submission failed');}}catch(error){if(msg)msg.textContent='Something went wrong. Please try again or email admin@autec.co.za.';}finally{if(submitButton)submitButton.disabled=false;}});}
