// Mobile navigation
const menuToggle=document.querySelector('.menu-toggle');const mainNav=document.querySelector('.main-nav');if(menuToggle&&mainNav){menuToggle.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open?'true':'false')});}
// Active navigation fallback
const currentPage=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.main-nav a').forEach(a=>{if(a.getAttribute('href')===currentPage){a.classList.add('active')}});
// Scroll reveal animations
const revealEls=document.querySelectorAll('.reveal');const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}})},{threshold:.12});revealEls.forEach(el=>revealObserver.observe(el));
// Gallery lightbox
const galleryItems=[...document.querySelectorAll('.gallery-item')];const lightbox=document.querySelector('.lightbox');if(galleryItems.length&&lightbox){const img=lightbox.querySelector('img');const close=lightbox.querySelector('.lightbox-close');const prev=lightbox.querySelector('.lightbox-prev');const next=lightbox.querySelector('.lightbox-next');let index=0;const openLightbox=i=>{index=i;img.src=galleryItems[index].src;img.alt=galleryItems[index].alt;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};const closeLightbox=()=>{lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow=''};const move=step=>{index=(index+step+galleryItems.length)%galleryItems.length;img.src=galleryItems[index].src;img.alt=galleryItems[index].alt};galleryItems.forEach((item,i)=>item.addEventListener('click',()=>openLightbox(i)));close.addEventListener('click',closeLightbox);prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(!lightbox.classList.contains('open'))return;if(e.key==='Escape')closeLightbox();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});}
// Static form feedback before Web3Forms submission
const form=document.querySelector('.contact-form');if(form){form.addEventListener('submit',()=>{const msg=form.querySelector('.form-message');if(msg)msg.textContent='Submitting your quote request...';});}
